-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
COUNT(DISTINCT ONLINE_SALE.user_id) AS PUCHASED_USERS, 
ROUND(COUNT(DISTINCT ONLINE_SALE.user_id)/
      (SELECT COUNT(user_id) FROM USER_INFO WHERE JOINED like '2021%'), 1) AS PUCHASED_RATIO
FROM user_info, online_sale
WHERE user_info.user_id = online_sale.user_id AND JOINED like '2021%'
GROUP BY MONTH
ORDER BY YEAR, MONTH;