-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(SALES_AMOUNT*PRICE) AS SALES
FROM PRODUCT, OFFLINE_SALE
WHERE PRODUCT.product_id = OFFLINE_SALE.product_id
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;