-- 코드를 입력하세요
SELECT a.APNT_NO AS APNT_NO, p.PT_NAME AS PT_NAME, p.PT_NO AS PT_NO, a.MCDP_CD AS MCDP_CD, d.DR_NAME AS DR_NAME, a.APNT_YMD AS APNT_YMD
FROM Patient p, Doctor d, Appointment a
WHERE p.PT_NO = a.PT_NO AND a.MDDR_ID = d.DR_ID AND APNT_YMD like '2022-04-13%' AND APNT_CNCL_YN like 'N' AND a.MCDP_CD = 'CS'
ORDER BY APNT_YMD;